### ISSUE TITLE
Use error codes in callbacks (irma.js)

### ISSUE THREAD

**Issue by aykevl** [credentials/irma_js#2]
Callbacks currently provide a textual (human-readable) string in English with an error message ([around here](https://github.com/credentials/irma_js/blob/master/client/irma.js#L604), for example). This should be an error code instead, because:

* it makes it possible to differentiate in the application between clicking "cancel" and hitting a timeout
* translation becomes easier

See:
https://github.com/credentials/irma_sms_issuer/blob/master/src/main/webapp/common.js#L114

**Comment by sietseringers** [comment]
Done.
